# Generated by Django 4.2.5 on 2023-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('tanggal_peminjaman', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
