# Generated by Django 4.2.5 on 2023-09-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tanggal_peminjaman',
            new_name='borrow_date',
        ),
    ]
